apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: rgs-demo
  namespace: fleet-default
spec:
  repo: "git@github.com:adamacosta/aws-rancher"
  revision: v0.1.0
  clientSecretName: ssh-key
  paths:
    - fleet
  targets:
    - name: all
      clusterSelector: {}