apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher
  namespace: kube-system
spec:
  chart: oci://registry.ranchercarbide.dev/charts/rancher
  createNamespace: true
  dockerRegistrySecret: 
    name: carbide-registry
  failurePolicy: reinstall
  targetNamespace: cattle-system
  valuesContent: |-
    auditLog:
      enabled: true
      level: 2
    hostname: rancher.rgsdemo.com
    ingress:
      tls:
        source: secret
    privateCA: true
    systemDefaultRegistry: registry.ranchercarbide.dev
  version: 2.14.2